# Configuration to create image
FROM node:alpine

WORKDIR '/app'

COPY package.json .
RUN npm install

# Copies everything from public and src dirs to working dir
COPY . .

CMD ["npm", "run", "start"]
